# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

enableRedis: true
enableMongo: true
enableHydra: true
enableCertIssuer: true

ingress:
  hostname: auth1.gke.protocol.one
  hostnamePrefix: ""
  path: /

certIssuer:
  email: admin@protocol.one

backend:
  name: gobackend
  role: gobackend
  image: "p1hub/p1auth1"
  imageTag: master-47
  port: 8080
  replicas: 1
  service: 
    type: ClusterIP
    port: 8080
    protocol: TCP
  env:
  - API_PORT
  - API_DEBUG
  - API_TIMEOUTREAD
  - API_TIMEOUTWRITE
  - API_ALLOWORIGINS
  - API_ALLOWCREDENTIALS
  - LOGGER_LEVEL
  - DATABASE_HOST
  - DATABASE_DATABASE
  - DATABASE_USER
  - DATABASE_PASSWORD
  - SESSION_DATABASE
  - SESSION_TABLE
  - SESSION_SECRET
  - SESSION_NAME
  - SESSION_MAXAGE
  - SESSION_ENSURETTL
  - HYDRA_PUBLICURL
  - HYDRA_ADMINURL
  - REDIS_ADDR
  - REDIS_PASSWORD

hydra:
  env:
  - SYSTEM_SECRET
  - DATABASE_URL
  - HTTPS_ALLOW_TERMINATION_FROM
  - LOG_LEVEL
  - ACCESS_TOKEN_LIFESPAN
  - ID_TOKEN_LIFESPAN
  - AUTHORIZE_CODE_LIFESPAN
  - OAUTH2_CONSENT_URL
  - OAUTH2_LOGIN_URL
  - OAUTH2_ISSUER_URL
  - OAUTH2_LOGOUT_REDIRECT_URL
  - OIDC_SUBJECT_TYPE_PAIRWISE_SALT

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
